export default{
    actionButton:{
        flexDirection:"row",
        justifyContent:"space-between",
        top:2
    },
    confirm:{
        flex:0.7,
        backgroundColor:"#3b5998",
        alignItems:"center",
        justifyContent:"center",
        borderRadius:10,
        height:30,
        bottom:3
    },

    delete:{
        marginLeft:5,
        flex:0.7,
        backgroundColor:"silver",
        alignItems:"center",
        justifyContent:"center",
        borderRadius:10,
        height:30,
        bottom:3
    },
    confirmText:{
        color:"#fff",
        fontSize:16
    },
    deleteText:{
        color:"#000",
        fontSize:16,
        fontWeight:"400"
    },
    friendRequest:{
        fontSize:17,
        fontWeight:"500",
        left:3
    },
    userDetail:{
        flexDirection:"column",
        left:5,
        flex:1
    },
    name:{
        fontSize:18,
        fontWeight:"400",
        color:"#000"
    },
    mutualFriends:{
        fontSize:16
    }
     
}